version: '3.8'

services:
  # --- Database ---
  db:
    container_name: pcshop-db
    image: mysql:8.0
    restart: always
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}         # Tạo user 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} # Đặt pass cho user \
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sample_database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pcshop-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

    # --- Redis ---
  redis:
    container_name: pcshop-redis
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - pcshop-network


  # --- Backend ---
  backend:
    container_name: pcshop-backend
    build: ./pcshopbackend/pcshop
    restart: always
    ports:
      - "${BACKEND_LOCAL_PORT}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET}
      - APP_UPLOAD_ROOT_DIR=/app/uploads
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pcshop-network

  # --- Frontend ---
  frontend:
    container_name: pcshop-frontend
    build: ./pcshopfrontend
    restart: always
    ports:
      - "${FRONTEND_LOCAL_PORT}:80" # Map 5173 (máy thật) -> 80 (container)
    depends_on:
      - backend
    networks:
      - pcshop-network

volumes:
  mysql_data:
  redis_data:

networks:
  pcshop-network:
    driver: bridge